# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://db:27017/event_ticketing
      - JWT_SECRET=your-secret-key
    volumes:
      - backend_data:/app/node_modules
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  backend_data:
  db_data:

networks:
  app-network:
    driver: bridge